CREATE TABLE vz_users_mail (jid int Primary key, mailfullname varchar(100), mailsystemid varchar(50), mailsystemurl varchar(100), mailsystemipaddress varchar(100), mailsystemtype varchar(50), provisioned_date varchar(50), provisioned_status varchar(50), deactivation_date varchar(50), provisioned_sourcetype varchar(50), mailvendorsource varchar(50), mailvendortype varchar(50), dynamicsid varchar(50), oracleid varchar(50), ncrid varchar(50), forwardemail varchar(150), regionalmailid varchar(50), regionalmailname varchar(50), organizationid varchar(50), homesiteid varchar(50), teleworkersiteid varchar(50), allowwebmail tinyint(1), vpngrp1 varchar(50), vpngrp1name varchar(50), vpnipdestination1 varchar(50), vpnipdestination2 varchar(50), vpnipdestination3 varchar(50), rsasecureidserialnumber varchar(100), socialextensions tinyint(1), google_email_address varchar(100), othersocial_email_address varchar(100), proximitysecurity varchar(50), sites_allowed1_id varchar(50), sites_allowed2_id varchar(50), sites_allowed3_id varchar(50), global_user tinyint(1), user_8021x_enabled tinyint(1), user_8021x_enforcementgroupid varchar(50), archiveautotype varchar(50), archiveautoname varchar(50), archivedestinationid varchar(100), two_factor_sms varchar(50), two_factor_email varchar(50), two_factor_lockretries varchar(10), googleidname varchar(100), gridid varchar(50), gridregion varchar(20), popallowed tinyint(1), imapallowed tinyint(1), vpn_expiration_date varchar(50), remotemailpassword varchar(50), remotemailpass_hash varchar(50))

Create table vz_users_famgroups (grpid int primary key, grpbtn char(50), grpbtnemail char(50), grpleaderid int(11), smallgroup tinyint(1), groupname char(100), familygroup tinyint(1), familyname char(100), grpteam0 int(11), grpteam1 int(11), grpteam2 int(11), grpteam3 int(11), grpteam4 int(11), grpteam5 int(11), grpteam6 int(11), grpteam7 int(11), grpteam8 int(11), grpteam9 int(11), fteam0 int(11), fteam1 int(11), fteam2 int(11), fteam3 int(11), fteam4 int(11), fteam5 int(11), fteam6 int(11), fteam7 int(11), fteam8 int(11), fteam9 int(11), largegroup tinyint(1), largegroup_inv_id char(100), largegroup_description char(100), affinitygroup tinyint(4), affinitydescription varchar(100), oracleid varchar(50), dynamicsid varchar(50), ncrid varchar(50), sequenceid int unique key auto_increment);

Create table vz_users_musicdj (djid int Primary key, djinvid char(50), mymusic1label char(50), mymusic1url char(100), mymusic2label char(50), mymusic2url char(100), mymusic3label char(50), mymusic3url char(100), mymusic4label char(50), mymusic4url char(100), mymusic5label char(50), mymusic5url char(100), youtubeurl varchar(100), youtubeloginblob varchar(200), oracleid varchar(50), dynamicsid varchar(50), ncrid varchar(50));

CREATE TABLE vz_users_location (uid int(11), locationfullcsv char(200), locationtime char(200), latitude varchar(50), longitude varchar(50), sequencenumber Primary int(11), cllpaddress varchar(100), cllporgid varchar(50), locationsource varchar(50), locationclient varchar(50), locationclientversion varchar(10));



// ALTER JOOMLA USERS TABLE IN VERSIONS 3.9-3.11 ALL

ALTER TABLE XXXX_USERS ADD COLUMN cllpaddress varchar(100), cllporgid varchar(50), securityphonenumber varchar(50), ncrid varchar(50), dynamicsid varchar(50), oracleid varchar(50), groupadmin tinyint(4)
familyadmin tinyint(4), premiumlocation tinyint(4), glibtnemail varchar(100), gliaccount varchar(50), glisubaccount varchar(50), isbusiness tinyint(1), erpaccountid varchar(50), erpsubaccountid varchar(50), erptype varchar(50), erpurl varchar(100), erpconnectionstring varchar(100), erpconnectionstringhash varchar(50), 

//GTV TABLE

create table vz_users_gtv (jid int primary key, ncrid varchar(50), dynamicsid varchar(50), oracleid varchar(50), espnplus tinyint(1), espnaccountnumber varchar(100), paramountplus tinyint(1), paramountaccountnumber varchar(100), userdefined1 varchar(50), userdefined2 varchar(50), userdefined3 varchar(50), userdefined4 varchar(50), userdefined5 varchar(50), espnstartdate varchar(50), espnenddate varchar(50), espnstatus varchar(10), espnstripereference varchar(100), cbsstripereference varchar(100), peacockstripereference varchar(100), peacocktv tinyint(1), usanetworks tinyint(1), peacockaccountnumber varchar(100), peacockstartdate varchar(50), peacockenddate varchar(50), usanetworksaccountnumber varchar(100), usastartdate varchar(50), usaenddate varchar(50), usastatus varchar(10), peacockstatus varchar(10), usanetworksstripereference varchar(100), netflixstatus tinyint(1), netflixaccountnumber varchar(100), netflixstartdate varchar(50), netflixenddate varchar(50), gtvstatus varchar(10), foxsports tinyint(1), foxsportsaccountnumber varchar(100), foxsportsstartdate varchar(50), foxsportsenddate varchar(50), foxsportsstatus varchar(10), foxsportsstripereference varchar(100), gtvstartdate varchar(50), gtvenddate varchar(50), gtvstripereference varchar(100), familygroupid varchar(50), familybtn


//PLATFORM MODULE SUBSCRIPTIONS BY CLASS

Create table vz_glicircus_subscriptions (id int Primary key, familyid char(50), grpid char(50), oracleid char(50),dynamicsid char(50), ncrid char(50), kdsid char(50), otherid1 char(50), otherid2 char(50), otherid3 char(50), otherid4 char(50), otherid5 char(50), otherid6 char(50), otherid7 char(50), otherid8 char(50), otherid9 char(50), otherid10 char(50), unified_com tinyint(1), unified_com_instance_inv_id char(50), email tinyint(1), email_instance_inv_id char(50), gtv tinyint(1), gtv_instance_inv_id char(50), vdj tinyint(1), vdj_instance_inv_id char(50), localvoice tinyint(1), localvoice_inv_id char(50), ldvoice tinyint(1), ldvoice_inv_id char(50), btn_telephone_id char(50), btn_email_id char(50), vurlhash1 char(100), vurlhash2 char(100), vurlhash3 char(100), vurlhash4 char(100), vurlhash5 char(100), vurlhash6 char(100), vurlhash7 char(100), vurlhash8 char(100), vurlhash9 char(100), vurlhash10 char(100), musicdjsubscription tinyint(1), unifiedsubscription tinyint(1), mailsubscription tinyint(1), gtvsubscription tinyint(1), gemsubscription tinyint(1), groupadministr

//UNIFIED AND VOICE

Create table vz_users_unifiedvoice (jid int primary key, oracleid varchar(50), dynamicsid varchar(50), ncrid varchar(50), btnphone varchar(50), extension varchar(10), appearance1_extension varchar(10), appearance1_name varchar(50), didtf1 varchar(50), didtf2 varchar(50), didtf3 varchar(50), didtf4 varchar(50), appearance2_extension varchar(10), appearance2_name varchar(50), phonesystemid varchar(50), phonesystemtype varchar(50), appearance3_extension varchar(10), appearance3_name varchar(50), mainring_extension varchar(50), mainring_name varchar(50), provisionedvoipid varchar(100), provisionedvoipsystemname varchar(100), provisionedvoipregionname varchar(50), provisionedvoipregionid varchar(50), imtype varchar(50), imshortname varchar(50), imgroup1 varchar(50), imgroup2 varchar(50), imgroup3 varchar(50), user_presence_status varchar(50), user_forward_tn1 varchar(50), user_forward_tn2 varchar(50), user_voicemail_pilot varchar(50), speeddial1 varchar(50), speeddial2 varchar(50), speeddial3 varchar(50), speeddial4 varchar(50), speeddial5 varchar(50), takebacktransferstring varchar(50), musicholdid varchar(50), ciscocallmanagerid varchar(50), 3cxid varchar(50), avayaid varchar(50), speeddial1name varchar(50), speeddial2name varchar(50), speeddial3name varchar(50), speeddial4name varchar(50), speeddial5name varchar(50), followme tinyint(4), followmedestination varchar(100), id int unique key auto_increment, phoneid int unique, phoneid_name varchar(100), fp_inventoryid varchar(50), user_voicemail_pilot_name varchar(100), siteid int(11), sitename varchar(100), subscribertype v

